### ISSUE TITLE
Make Database and Checking Error

### ISSUE THREAD

**Issue by hmwoliul** [databitty/365#4]
- [x] Make Database
- [x] Connect Database
- [x] Make a Success Massage for Connecting Data (Only Dialog)
- [x] Make a Error Massage for Connecting Data (Only Dialog)
- [x] Make a page after Sign in. (Another Page For Success)

**Comment by hmwoliul** [comment]
@AH-Rifat I need SQL file.

**Comment by AH-Rifat** [comment]
disi

**Comment by AH-Rifat** [comment]
@hmwoliul @databitty/startup Issue Complete. 👍
