### ISSUE TITLE
Modification

### ISSUE THREAD

**Issue by hmwoliul** [databitty/365#8]
**PHP and HTML**
- [x] Make input connection from front end

- [x] View User name in all page after login.

**SQL**
- [x] Make Table named "ADMIN", "MEMBER", "GUEST"

- [x] Make ROW named "FIRST NAME, LAST NAME,USERNAME, EMAIL, PASSWORD"

**Comment by hmwoliul** [comment]
Use this code.

`<h2 id="searchForm">
          <font size="+2" color="#006633">
            <?php
            include('connection.php');
            session_start();
            echo "Hi ";
            echo $_SESSION ['user'];
            ?>
            <a href="logout.php">
              <?php
              if(isset($_SESSION['id']))
              {
                echo "Logout";
              }
              ?>
            </a>
          </font>
        </h2>`

**Comment by AH-Rifat** [comment]
<?php
session_start();
include_once 'dbconnect.php';

if(isset($_SESSION['user'])!="")
{
 header("Location: home.php");
}
if(isset($_POST['btn-login']))
{
 $email = mysql_real_escape_string($_POST['email']);
 $upass = mysql_real_escape_string($_POST['pass']);
 $res=mysql_query("SELECT * FROM users WHERE email='$email'");
 $row=mysql_fetch_array($res);
 if($row['password']==md5($upass))
 {
  $_SESSION['user'] = $row['user_id'];
  header("Location: home.php");
 }
 else
 {
  ?>
        <script>alert('wrong details');</script>
        <?php
 }
 
}
?>

**Comment by hmwoliul** [comment]
Use this code in every page

`<?php
session_start();
include_once 'dbconnect.php';`

**Comment by hmwoliul** [comment]
Use userid, user, password row

**Comment by hmwoliul** [comment]
here **user** is **username**

**Comment by AH-Rifat** [comment]
@hmwoliul 
#8 **SQL    `Done`**

**Comment by hmwoliul** [comment]
User name in every page (PHP and HTML)
